<section id="catalog-history" class="catalog-history"><div class="page-heading"><div><div class="eyebrow">ACOMPANHE SUAS COMPRAS</div><h2>Meus pedidos</h2><p>Pedidos feitos neste navegador. Atualize para consultar o andamento.</p></div><a class="button secondary" href="{{ url('/catalog/'.$company->slug) }}#catalog-history">Atualizar status</a></div>
@forelse($history as $purchase)
@php($cancelled = $purchase->status === 'cancelled' || $purchase->sale_status === 'cancelled')
<article class="catalog-history-card"><div class="metric-row"><div><strong>Pedido #{{ $purchase->id }}</strong><small>{{ \Carbon\Carbon::parse($purchase->created_at)->timezone($company->timezone)->format('d/m/Y H:i') }}</small></div><span class="badge {{ $cancelled ? 'catalog-cancelled' : '' }}">{{ $cancelled ? 'Cancelado' : ($purchase->sale_id ? 'Registrado' : 'Aguardando confirmação') }}</span></div>
@if(!$cancelled)<p class="catalog-order-stage">{{ $purchase->order_status ? config('poseitech.order_statuses.'.$purchase->order_status) : 'Recebido pela loja' }}</p><ol class="catalog-progress">@php($steps=['received'=>'Recebido','confirmed'=>'Confirmado','preparing'=>'Em preparo','ready'=>'Pronto','shipping'=>'Em entrega','delivered'=>'Concluído'])@php($steps=empty($purchase->order_delivery) ? array_diff_key($steps,['shipping'=>true]) : $steps)
@php($current=array_search($purchase->order_status ?? 'received',array_keys($steps)))@foreach($steps as $step=>$label)<li class="{{ $loop->index <= $current ? 'complete' : '' }}">{{ $label }}</li>@endforeach</ol>@endif
<details><summary>Ver itens e detalhes</summary><ul>@foreach(json_decode($purchase->items,true) as $item)<li>{{ $item['quantity'] }} × {{ $item['name'] }} — {{ \App\Services\Tenant::money($item['price']*$item['quantity']) }}</li>@endforeach</ul>@if($purchase->address)<p>Endereço: {{ $purchase->address }}</p>@endif<p>{{ $purchase->notes }}</p><p>Valor solicitado: {{ \App\Services\Tenant::money($purchase->total) }}</p>@if($purchase->sale_id)<p>Venda #{{ $purchase->sale_id }} · Valor registrado: <strong>{{ \App\Services\Tenant::money($purchase->registered_total) }}</strong></p>@endif</details>
@if($checkout)<div class="actions"><button type="button" class="secondary catalog-reorder" data-items="{{ $purchase->items }}">Adicionar itens ao carrinho</button><small>Preços e disponibilidade atuais serão considerados.</small></div>@endif</article>
@empty<div class="catalog-history-card"><h3>Seu histórico começa aqui</h3><p>Após enviar um pedido, acompanhe nesta área a confirmação e cada etapa do atendimento.</p></div>@endforelse{{ $history->links() }}<p class="muted">O histórico depende do cookie privado deste navegador. Limpar os cookies ou usar outro dispositivo não recupera pedidos automaticamente.</p>
</section>
