@extends('layout',['public'=>true])
@section('title',$company->name)
@section('content')
@php($checkout = ($company->settings['catalog_checkout'] ?? false) && $company->enabled('orders'))
@php($color = $company->settings['catalog_color'] ?? '#155e75')
<link rel="stylesheet" href="{{ asset('assets/catalog.css') }}?v={{ filemtime(public_path('assets/catalog.css')) }}">
<script src="{{ asset('assets/catalog.js') }}?v={{ filemtime(public_path('assets/catalog.js')) }}" defer></script>
<div class="catalog-store" style="--catalog-color:{{ preg_match('/^#[a-fA-F0-9]{6}$/',$color) ? $color : '#155e75' }}" data-company="{{ $company->id }}" data-submitted="{{ session('catalog_submitted') ? 1 : 0 }}" data-currency="{{ $company->currency }}">
<header class="catalog-hero"><div class="catalog-identity">@if($company->logo)<img src="{{ url('/logo/'.$company->id) }}" alt="Logo {{ $company->name }}">@endif<span>{{ $company->name }}</span></div><div class="eyebrow">ESCOLHIDO PARA VOCÊ</div><h1>{{ ($company->settings['catalog_title'] ?? '') ?: 'Encontre seu próximo favorito.' }}</h1><p>{{ ($company->settings['catalog_description'] ?? '') ?: 'Explore nossos produtos e serviços. Qualidade e cuidado em cada escolha.' }}</p><div class="actions"><a class="button secondary" href="#catalog-history">Meus pedidos</a>@if($checkout)<a class="button" href="#catalog-cart">Montar meu pedido</a>@endif @if($company->whatsapp)<a class="button secondary" href="https://wa.me/{{ preg_replace('/\D/','',$company->whatsapp) }}" rel="noopener" target="_blank">Fale com a loja</a>@endif</div>@if($company->address)<small>{{ $company->address }}</small>@endif</header>
<div class="catalog-toolbar"><label>Encontre o que procura<input id="catalog-search" type="search" placeholder="Pesquisar produtos e serviços"></label><label>Categoria<select id="catalog-category"><option value="">Todas as categorias</option>@foreach($products->pluck('category')->filter()->unique() as $category)<option>{{ $category }}</option>@endforeach</select></label><label>Ordenar<select id="catalog-sort"><option value="name">Nome</option><option value="price-low">Menor pre?o</option><option value="price-high">Maior pre?o</option></select></label><span id="catalog-count" role="status"></span></div>
<div class="catalog-layout"><section class="catalog-products">@forelse($products as $p)
@php($unavailable = $company->enabled('stock') && $p->type === 'product' && $p->stock <= 0)
<article class="catalog-product" data-id="{{ $p->id }}" data-name="{{ $p->name }}" data-category="{{ $p->category }}" data-price="{{ $p->price }}">
<div class="catalog-picture">@if($p->image)<img src="{{ url('/media/'.$company->id.'/'.$p->id) }}" alt="{{ $p->name }}" loading="lazy">@else<span aria-hidden="true">{{ $p->type === 'service' ? '✦' : '◇' }}</span>@endif<span class="catalog-tag">{{ $p->category ?: ($p->type === 'service' ? 'Serviço' : 'Produto') }}</span></div>
<div class="catalog-product-content"><h2>{{ $p->name }}</h2><p>{{ $p->description }}</p><strong class="catalog-price">{{ \App\Services\Tenant::money($p->price) }}</strong>
@if($checkout && !$unavailable)@foreach(json_decode($p->addons ?? '[]',true) as $index=>$addon)<label class="check"><input type="checkbox" class="catalog-addon" value="{{ $index }}" data-price="{{ $addon['price'] }}">{{ $addon['name'] }} + {{ \App\Services\Tenant::money($addon['price']) }}</label>@endforeach<label>Quantidade<input class="catalog-quantity" type="number" value="0" min="0" max="{{ $company->enabled('stock') && $p->type === 'product' ? min(10000,$p->stock) : 10000 }}" aria-label="Quantidade de {{ $p->name }}"></label><button type="button" class="catalog-add">+ Adicionar</button>@elseif($unavailable)<span class="badge">Indisponível no momento</span>@else<span class="muted">Consulte a loja para comprar</span>@endif</div></article>
@empty<p>Nossa vitrine está sendo preparada. Fale com a loja para conhecer as novidades.</p>@endforelse<p id="catalog-empty" hidden>Nenhum item encontrado. Experimente outro nome ou categoria.</p></section>
@if($checkout)<aside id="catalog-cart"><form method="post" action="{{ url('/catalog/'.$company->slug) }}" class="card" id="catalog-checkout" data-old-items="{{ json_encode(old('items',[])) }}">@csrf<input type="hidden" name="request_key" value="{{ old('request_key',(string)\Illuminate\Support\Str::uuid()) }}"><div class="metric-row"><h2>Seu carrinho</h2><button type="button" class="secondary" id="catalog-clear">Limpar</button></div><p id="catalog-cart-notice" role="status"></p><div id="catalog-cart-items" aria-live="polite">Escolha seus favoritos na vitrine.</div><div class="metric-row total"><span>Subtotal</span><strong id="catalog-total">{{ \App\Services\Tenant::money(0) }}</strong></div><p class="muted">Frete e pagamento a combinar. O pedido será confirmado pela equipe.</p><label>Seu nome<input name="name" required maxlength="160" autocomplete="name" value="{{ old('name') }}"></label><label>Telefone / WhatsApp<input name="phone" type="tel" data-phone required maxlength="30" autocomplete="tel" value="{{ old('phone') }}"></label><label>Endereço (para entrega)<input name="address" maxlength="255" autocomplete="street-address" value="{{ old('address') }}"></label><label>Observações<textarea name="notes" maxlength="1000">{{ old('notes') }}</textarea></label><div id="catalog-inputs"></div><button class="full-width" id="catalog-send" disabled>Enviar pedido à loja</button><small>Seus dados serão usados para atender este pedido.</small></form></aside>@endif</div>@include('components.catalog-history')@if($checkout)<a href="#catalog-cart" class="catalog-cart-bar">Ver carrinho <strong id="catalog-bar-total"></strong></a>@endif</div>
@endsection
