@extends('layout',['public'=>true])
@section('title','Portal do cliente')
@section('content')
<div class="page-heading"><div><div class="eyebrow">{{ $company->name }}</div><h1>Olá, {{ $customer->name }}</h1><p>Compras referentes a {{ $monthLabel }}.</p></div>
<form method="post" action="{{ url('/portal/logout') }}">@csrf<button class="secondary">Sair do portal</button></form></div>
<form class="filters"><label>Mês de referência<input type="month" name="month" value="{{ $month }}" required></label><label>Tipo<select name="kind">@foreach(['all'=>'Todas','fiado'=>'Compras feitas no fiado','paid'=>'Compras quitadas','wallet'=>'Pagas com saldo da conta'] as $key=>$label)<option value="{{ $key }}" @selected(request('kind','all')===$key)>{{ $label }}</option>@endforeach</select></label><label>Status<select name="status">@foreach(['all'=>'Todos','completed'=>'Concluídas','cancelled'=>'Canceladas'] as $key=>$label)<option value="{{ $key }}" @selected(request('status','all')===$key)>{{ $label }}</option>@endforeach</select></label><label>Número da compra<input type="number" name="purchase" min="1" value="{{ request('purchase') }}"></label><button>Filtrar</button><a href="{{ url('/portal') }}">Limpar filtros</a></form>
<div class="kpi-grid"><div class="kpi"><span>Comprado em {{ $monthLabel }}</span><strong>{{ \App\Services\Tenant::money($totals->total) }}</strong></div><div class="kpi"><span>Pago nas compras do mês</span><strong>{{ \App\Services\Tenant::money($totals->paid) }}</strong></div>
@if($accounts->isNotEmpty())<div class="kpi"><span>Valores em aberto (todos os meses)</span><strong>{{ \App\Services\Tenant::money($accounts->sum(fn($a)=>$a->amount-$a->paid)) }}</strong></div>@endif</div>
<div class="kpi-grid"><div class="kpi"><span>Comprado no fiado em {{ $monthLabel }}</span><strong>{{ \App\Services\Tenant::money($fiadoMonth) }}</strong></div><div class="kpi"><span>Fiado em aberto das compras de {{ $monthLabel }}</span><strong>{{ \App\Services\Tenant::money($debtMonth) }}</strong></div><div class="kpi"><span>Fiado em aberto total</span><strong>{{ \App\Services\Tenant::money($debtTotal) }}</strong></div></div>
<p class="muted">Os indicadores consideram o mês de referência e a dívida total atual. Os filtros abaixo selecionam as compras, sem alterar os valores desses indicadores.</p>
<section class="card"><h2>Compras de {{ $monthLabel }}</h2><div class="table-wrap"><table><thead><tr><th>Número da compra</th><th>Valor</th><th>Comprovante</th></tr></thead><tbody>
@forelse($sales as $sale)<tr><td>#{{ $sale->id }} @if($sale->status==='cancelled')<span class="badge danger">Cancelada</span>@elseif($sale->fiado_amount>0)<span class="badge">{{ $sale->paid >= $sale->total?'Fiado quitado':'Fiado' }}</span>@else<span class="badge">Pago</span>@endif @if($sale->wallet_used>0)<small>Pago com saldo da conta: {{ \App\Services\Tenant::money($sale->wallet_used) }}</small>@endif</td><td>{{ \App\Services\Tenant::money($sale->total) }}@if($sale->fiado_amount>0)<small>Fiado na compra: {{ \App\Services\Tenant::money($sale->fiado_amount) }}</small>@endif</td><td><a href="{{ url('/receipt/'.$sale->receipt_hash) }}" target="_blank" rel="noopener">Ver comprovante ↗</a></td></tr>
@empty<tr><td colspan="3">Nenhuma compra para os filtros selecionados.</td></tr>@endforelse
</tbody></table></div>{{ $sales->links() }}</section>
@if($accounts->isNotEmpty())<section class="card"><h2>Valores pendentes</h2><p class="muted">Somente valores ainda em aberto, incluindo meses anteriores.</p>@include('components.accounts',['readonly'=>true])</section>@endif
@endsection
