<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BusinessController;
use App\Http\Controllers\CampaignController;
use App\Http\Controllers\PortalController;
use App\Http\Controllers\ResourceController;
use App\Http\Controllers\SettingsController;
use Illuminate\Support\Facades\Route;

Route::get('/', fn () => redirect(auth()->check() ? '/dashboard' : '/login'));
Route::middleware('guest')->group(function () {
    Route::get('/login', fn () => view('auth', ['mode' => 'login']))->name('login');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:10,1');
    Route::get('/register', fn () => view('auth', ['mode' => 'register']));
    Route::post('/register', [AuthController::class, 'register'])->middleware('throttle:5,60');
    Route::get('/forgot-password', fn () => view('auth', ['mode' => 'forgot']))->name('password.request');
    Route::post('/forgot-password', [AuthController::class, 'forgot'])->middleware('throttle:3,1');
    Route::get('/reset-password/{token}', fn ($token) => view('auth', ['mode' => 'reset', 'token' => $token]))->name('password.reset');
    Route::post('/reset-password', [AuthController::class, 'reset'])->middleware('throttle:5,1');
});
Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth');
Route::get('/portal/access/{token}', [PortalController::class, 'access'])->middleware('throttle:10,1');
Route::get('/portal', [PortalController::class, 'home']);
Route::post('/portal/logout', [PortalController::class, 'logout']);
Route::get('/receipt/{token}', [PortalController::class, 'receipt'])->where('token', '[a-f0-9]{64}')->middleware('throttle:60,1');
Route::get('/catalog/{slug}', [PortalController::class, 'catalog']);
Route::get('/media/{companyId}/{productId}', [PortalController::class, 'image'])->whereNumber(['companyId', 'productId']);
Route::get('/logo/{companyId}', [PortalController::class, 'logo'])->whereNumber('companyId');
Route::middleware(['auth', 'can:platform'])->group(function () {
    Route::get('/admin', [AdminController::class, 'index']);
    Route::post('/admin/companies/{id?}', [AdminController::class, 'company']);
    Route::post('/admin/plans/{id?}', [AdminController::class, 'plan']);
    Route::post('/admin/support/{id}', [AdminController::class, 'support']);
    Route::post('/admin/leave', [AdminController::class, 'leave']);
    Route::post('/admin/settings', [AdminController::class, 'settings']);
});
Route::middleware(['auth', 'company'])->group(function () {
    Route::get('/dashboard', [BusinessController::class, 'dashboard']);
    Route::get('/opportunities', [BusinessController::class, 'opportunities']);
    Route::get('/search', [BusinessController::class, 'search']);
    Route::get('/records/{resource}', [ResourceController::class, 'index']);
    Route::get('/records/{resource}/new', [ResourceController::class, 'form']);
    Route::get('/records/{resource}/{id}/edit', [ResourceController::class, 'form'])->whereNumber('id');
    Route::post('/records/{resource}/{id?}', [ResourceController::class, 'save'])->whereNumber('id');
    Route::get('/customers/{id}', [ResourceController::class, 'customer'])->whereNumber('id');
    Route::post('/customers/{id}/privacy', [ResourceController::class, 'privacy'])->whereNumber('id');
    Route::post('/customers/{id}/portal', [PortalController::class, 'issue'])->whereNumber('id');
    Route::post('/customers/{id}/redeem', [BusinessController::class, 'redeem'])->whereNumber('id');
    Route::post('/customers/{id}/credits', [BusinessController::class, 'creditAdjustment'])->whereNumber('id');
    Route::get('/sales', [BusinessController::class, 'sales']);
    Route::get('/sales/new', [BusinessController::class, 'saleForm']);
    Route::post('/sales', [BusinessController::class, 'sell']);
    Route::get('/sales/{id}', [BusinessController::class, 'sale'])->whereNumber('id');
    Route::post('/sales/{id}/cancel', [BusinessController::class, 'cancel'])->whereNumber('id');
    Route::post('/sales/{id}/email', [CampaignController::class, 'receipt'])->whereNumber('id')->middleware('throttle:5,1');
    Route::get('/cash', [BusinessController::class, 'cash']);
    Route::post('/cash', [BusinessController::class, 'cashAction']);
    Route::get('/finance', [BusinessController::class, 'finance']);
    Route::get('/credit', [BusinessController::class, 'finance']);
    Route::post('/accounts', [BusinessController::class, 'account']);
    Route::post('/accounts/{id}/pay', [BusinessController::class, 'settle'])->whereNumber('id');
    Route::post('/accounts/{id}/email', [CampaignController::class, 'billing'])->whereNumber('id')->middleware('throttle:5,1');
    Route::post('/reports/email', [CampaignController::class, 'report'])->middleware('throttle:3,1');
    Route::get('/stock', [BusinessController::class, 'stock']);
    Route::post('/stock', [BusinessController::class, 'stockAction']);
    Route::get('/orders', [BusinessController::class, 'orders']);
    Route::post('/orders/{id}', [BusinessController::class, 'orderAction'])->whereNumber('id');
    Route::get('/reports', [BusinessController::class, 'reports']);
    Route::get('/alerts', [BusinessController::class, 'alerts']);
    Route::post('/alerts/{id}', [BusinessController::class, 'readAlert'])->whereNumber('id');
    Route::get('/campaigns', [CampaignController::class, 'index']);
    Route::post('/campaigns', [CampaignController::class, 'store']);
    Route::post('/campaigns/{id}/send', [CampaignController::class, 'send'])->whereNumber('id')->middleware('throttle:3,1');
    Route::get('/settings', [SettingsController::class, 'index']);
    Route::post('/settings', [SettingsController::class, 'save']);
    Route::post('/staff/{id?}', [SettingsController::class, 'staff'])->whereNumber('id');
});
